### ISSUE TITLE
Choice of Org / Repo name.

### ISSUE THREAD

**Issue by ghost** [EmeraldFreedom/EmeraldFreedomMod-New#1]
Hello, as you may not know me a @reuben4545 used to own a server called EmeraldFreedom.

And therefore the name is mine. If you would like to use this name. Either make me a developer and give me credit. Or delete/re-name this repository/organisation.

**Comment by DUFCLiam** [comment]
There was not any copyright and you shall not be added :) Have a nice day if you have anymore things to say feel free to tag me :)

**Comment by ghost** [comment]
@DUFCLiam can I join MCPluginDev

**Comment by DUFCLiam** [comment]
@ItsFenixMC, You must contribute to the code more that the avarage user.
